_target_: src.criteria.GOTDSetCriterion.GOTDSetCriterion

matcher: ${matcher}

losses:
  loss_bbox:
    _target_: src.criteria.losses.BoxesLoss.BoxesLoss
    loss_l1_weight: 1
    loss_giou_weight: 2.5
    loss_weight: 2
  loss_label:
    _target_: src.criteria.losses.LabelLoss.LabelLoss
    eos_coeff: 0.1
    num_classes: ${model.net.num_classes}
    loss_weight: 1
